# Task : Session 1
Solve these questions own your own and try to test yourself what you have learned in the session.

Happy Learning!

### Q1 :- Print the given strings as per stated format.

**Given strings**:
```
"Data" "Science" "Mentorship" "Program"
"By" "CampusX"
```
**Output**:
```
Data-Science-Mentorship-Program-started-By-CampusX
```

Concept- [Seperator and End]

In [ ]:
print("Data","Science","Mentorship","Program",sep='-',end='-started-')
print("By","CampusX",sep='-')

Data-Science-Mentorship-Program-started-By-CampusX

### Q2:- Write a program that will convert celsius value to fahrenheit.

In [ ]:
celcius=int(input("Enter temperature in celcius:"))
fahrenheit=(celcius*9/5)+32
print(fahrenheit)

Enter temperature in celcius:5
41.0

### Q3:- Take 2 numbers as input from the user.Write a program to swap the numbers without using any special python syntax.

In [ ]:
a = int(input("Enter first number: "))
b = int(input("Enter second number: "))
temp = a
a = b
b = temp
print(a,b)

Enter first number: 98
Enter second number: 59
59 98

### Q4:- Write a program to find the euclidean distance between two coordinates.Take both the coordinates from the user as input.

In [2]:
x1=int(input("Enter x1:"))
y1=int(input("Enter y1:"))
x2=int(input("Enter x2:"))
y2=int(input("Enter y2:"))
euclean_distance=((x2-x1)**2+(y2-y1)**2)**0.5
print(euclean_distance)

Enter x1:5
Enter y1:4
Enter x2:3
Enter y2:2
2.8284271247461903

### Q5:- Write a program to find the simple interest when the value of principle,rate of interest and time period is provided by the user.

In [ ]:
principal=int(input("Enter pricipal amount:"))
rate_of_interest=int(input("Enter rate of interest:"))
time=int(input("Enter time:"))
simple_interest=(principal*rate_of_interest*time)/100
print(simple_interest)

Enter pricipal amount:50
Enter rate of interest:5
Enter time:5
12.5

### Q6:- Write a program that will tell the number of dogs and chicken are there when the user will provide the value of total heads and legs.

For example:
Input:
heads -> 4
legs -> 12
<br>
Output:
dogs -> 2
chicken -> 2

In [ ]:
heads=4
legs=12

### Q7:- Write a program to find the sum of squares of first n natural numbers where n will be provided by the user.

In [ ]:
n=int(input("Enter number:"))
sum_of_squares= n * (n + 1) * (2 * n + 1) / 6
print(sum_of_squares)

Enter number:5
55.0

### Q8:- Given the first 2 terms of an Arithmetic Series.Find the Nth term of the series. Assume all inputs are provided by the user.

In [ ]:
term1=int(input("Enter first term:"))
term2=int(input("Enter second term:"))

### Q9:- Given 2 fractions, find the sum of those 2 fractions.Take the numerator and denominator values of the fractions from the user.

In [ ]:
a=int(input("Enter first numerator:"))
b=int(input("Enter first denominator:"))
c=int(input("Enter second numerator:"))
d=int(input("Enter second denominator:"))
sum_of_fractions=(a*d+b*c)/(b*d)
print(sum_of_fractions)

Enter first numerator:1
Enter first denominator:2
Enter second numerator:1
Enter second denominator:3
0.8333333333333334

### Q10:- Given the height, width and breadth of a milk tank, you have to find out how many glasses of milk can be obtained? Assume all the inputs are provided by the user.



Input:<br>
Dimensions of the milk tank<br>
H = 20cm, L = 20cm, B = 20cm
<br><br>
Dimensions of the glass<br>
h = 3cm, r = 1cm

In [1]:
H=20
L=20
B=20
h=3
r=1
volume_of_milk_tank=H*L*B
volume_of_glass=3.14*r*r*h
no_of_glasses=volume_of_milk_tank/volume_of_glass
print(no_of_glasses)

849.2569002123142